apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: checkout
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: checkout
  namespaceSelector:
    matchNames:
    - retail-store-prod
  endpoints:
  - port: http
    path: /metrics
    interval: 30s