{{- if (index .Values .Release.Name).hasDatabase }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db
    spec:
      containers:
      - name: db
        image: {{ (index .Values .Release.Name).dbImage }}
        env:
        {{- if index .Values .Release.Name "dbEnv" }}
        {{- toYaml (index .Values .Release.Name "dbEnv") | nindent 8 }}
        {{- end }}
        ports:
        - containerPort: {{ (index .Values .Release.Name).dbPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
spec:
  selector:
    app: {{ .Release.Name }}-db
  ports:
    - port: {{ (index .Values .Release.Name).dbPort }}
      targetPort: {{ (index .Values .Release.Name).dbPort }}
{{- end }}
