apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout-db
  template:
    metadata:
      labels:
        app: checkout-db
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379