name: 🚀 UI CI

on:
  push:
    paths:
      - 'src/ui/**'
    branches:
      - main

jobs:
  call-security-pipeline:
    uses: ./.github/workflows/security-pipeline.yml
    with:
      image_name: "retail-ui"
      context: "./src/ui/"
    secrets: inherit 
  
  update-manifests:
    needs: call-security-pipeline
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "retail-ui"
    steps:
    - name: 📥 Checkout Manifests
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITOPS_TOKEN }} 
    - name: 📝 Update Kustomize Tag
      run: |
          # Use Kustomize to update the image tag to the current Git SHA
          cd k8s/overlays/production
          kustomize edit set image ${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}=${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: 🚀 Push to GitHub
      run: |
          git config --global user.name "GitOps-Bot"
          git config --global user.email "bot@gadget-store.com"
          git add .
          git commit -m "deploy: update ${{ env.IMAGE_NAME }} to ${{ github.sha }} [skip ci]"
          git push
