name: 🚀 UI CI

on:
  push:
    paths:
      - 'src/ui/**'
    branches:
      - main

jobs:
  call-security-pipeline:
    uses: ./.github/workflows/security-pipeline.yml
    with:
      image_name: "retail-ui"
      context: "./src/ui/"
    secrets: inherit 